### ISSUE TITLE
Vagrantfile de kali Linux roto

### ISSUE THREAD

**Issue by IgnacioPardo** [pablorubinstein/utdt-introsec#1]
En el [Vagrantfile de Kali Linux](https://github.com/pablorubinstein/utdt-introsec/blob/main/vagrant/kali/Vagrantfile) la linea 11 donde dice:
`  config.vm.box_version = "2023.4.0`
falta la comilla de cierre:
`  config.vm.box_version = "2023.4.0"`

**Comment by pablorubinstein** [comment]
Solucionado en e409c5c. Gracias!
